services:
  api:
    build: .
    container_name: "spare-api"
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
      - ./node_modules/:/app/node_modules
    depends_on:
      - db
  db:
    image: mysql:lts
    ports:
      - 3306:3306
    container_name: "mysql-db"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}

    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d:ro

volumes:
  mysql-data:
